# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2

# YAML Anchors and Aliases
# https://circleci.com/docs/2.0/writing-yaml/
# https://circleci.com/blog/circleci-hacks-reuse-yaml-in-your-circleci-config-with-yaml/

# Download and cache dependencies
# https://circleci.com/docs/2.0/yarn/
# https://circleci.com/docs/2.0/caching/
_restore_yarn_cache: &restore_yarn_cache
  keys:
    - yarn-packages-{{ checksum "yarn.lock" }}

_save_yarn_cache: &save_yarn_cache
  key: yarn-packages-{{ checksum "yarn.lock" }}
  paths:
    - ~/.cache/yarn

_link_self_as_dependency: &link_self_as_dependency
  name: 'Link `eslint-config-ai` as a dependency'
  command: |
    yarn link
    yarn link eslint-config-ai

_defaults: &defaults
  steps:
    - run: node -v
    - checkout
    - restore_cache: *restore_yarn_cache
    - run: yarn install --frozen-lockfile
    - save_cache: *save_yarn_cache
    - run: *link_self_as_dependency
    - run: npm run lint

# Setup

jobs:
  node-current:
    <<: *defaults
    docker:
      - image: cimg/node:current
  node-lts:
    <<: *defaults
    docker:
      - image: cimg/node:lts
  node-maintenance:
    <<: *defaults
    docker:
      - image: cimg/node:18.12.0

workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-current
      - node-lts
      - node-maintenance
