# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/language-javascript/ for more details
version: 2.1

# YAML Anchors and Aliases
# - https://circleci.com/docs/introduction-to-yaml-configurations/
# - https://circleci.com/blog/circleci-hacks-reuse-yaml-in-your-circleci-config-with-yaml/

# Download and cache dependencies
# - https://circleci.com/docs/caching/
# - https://pnpm.io/continuous-integration#circleci
_restore_pnpm_cache: &restore_pnpm_cache
  name: Restore pnpm Package Cache
  keys:
    - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}

_save_pnpm_cache: &save_pnpm_cache
  name: Save pnpm Package Cache
  key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
  paths:
    - .pnpm-store

_link_self_as_dependency: &link_self_as_dependency
  name: 'Link `eslint-config-ai` as a dependency'
  command: |
    pnpm link --global
    pnpm link --global eslint-config-ai

_defaults: &defaults
  steps:
    - run: node -v
    - checkout
    - restore_cache: *restore_pnpm_cache
    - run: pnpm -v
    - run:
        # Do I need this?
        # corepack prepare pnpm@latest-9 --activate
        name: Install pnpm package manager
        command: |
          corepack enable
          pnpm config set store-dir .pnpm-store
    - run: pnpm -v
    - run: pnpm install --frozen-lockfile
    - save_cache: *save_pnpm_cache
    - run: *link_self_as_dependency
    - run: pnpm lint

# Setup
jobs:
  node-current:
    <<: *defaults
    docker:
      - image: cimg/node:current
  node-lts:
    <<: *defaults
    docker:
      - image: cimg/node:lts
  node-maintenance:
    <<: *defaults
    docker:
      - image: cimg/node:18.12.0

workflows:
  version: 2
  node-multi-build:
    jobs:
      - node-current
      - node-lts
      - node-maintenance
